services:
  - type: web
    name: blog-website
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput"
    startCommand: "gunicorn blog-website.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: django_project.settings
