# Generated by Django 5.2.6 on 2025-10-15 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_image'),
        ('users', '0002_profile_bio_profile_location_profile_website'),
    ]

    operations = [
    ]
